server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
        - id: product-service
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**,/api/v1/communication/**

eureka:
  instance:
      prefer-ip-address: true
      ip-address: ${HOST_IP:127.0.0.1}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
