server:
  port: 8083

spring:
  application:
    name: orders
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/order_db
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true